/** Local menu catalog — Angie’s Food Truck (fallback until Google Sheet is wired). */
import { gallerySrc } from "@/lib/data/gallery-path";
import type { MenuItem } from "./schema";
import {
  ANGIES_ADD_EXTRA_SUB,
  ANGIES_BURRITO_MEAT,
  ANGIES_STREET_TACO_MEAT,
} from "@/lib/menu/angies-modifier-groups";

export const localMenuItems: MenuItem[] = [
  {
    id: "tacos-street",
    active: true,
    category: "Tacos",
    sortOrder: 1,
    name: "Street Tacos",
    description: "Mexican street tacos. Confirm meats, toppings, and price with the owner.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("food8.jpg"),
    imageAlt: "Street tacos",
    optionGroups: [ANGIES_STREET_TACO_MEAT, ...ANGIES_ADD_EXTRA_SUB],
  },
  {
    id: "birria-main",
    active: true,
    category: "Birria",
    sortOrder: 1,
    name: "Birria",
    description:
      "Beef birria mentioned publicly. Confirm whether served as tacos, plate, or consommé.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("food10.jpg"),
    imageAlt: "Birria",
    optionGroups: [...ANGIES_ADD_EXTRA_SUB],
  },
  {
    id: "burrito-main",
    active: true,
    category: "Burritos",
    sortOrder: 1,
    name: "Burrito",
    description:
      "12″ flour tortilla with cheese, rice, beans, meat, and salsa. Choose meat at order.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("food11.jpg"),
    imageAlt: "Burrito",
    optionGroups: [ANGIES_BURRITO_MEAT, ...ANGIES_ADD_EXTRA_SUB],
  },
  {
    id: "agua-horchata",
    active: true,
    category: "Aguas Frescas",
    sortOrder: 1,
    name: "Horchata",
    description: "Classic rice cinnamon horchata.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("drink1.jpg"),
    imageAlt: "Horchata",
  },
  {
    id: "agua-mango",
    active: true,
    category: "Aguas Frescas",
    sortOrder: 2,
    name: "Mango Fresh Water",
    description: "Mango agua fresca.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("drink.jpg"),
    imageAlt: "Mango fresh water",
  },
  {
    id: "agua-rotating",
    active: true,
    category: "Aguas Frescas",
    sortOrder: 3,
    name: "Aguas Frescas",
    description: "Fresh waters — confirm flavors with the owner.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("drink2.png"),
    imageAlt: "Aguas frescas",
  },
  {
    id: "special-daily",
    active: true,
    category: "Specials",
    sortOrder: 1,
    name: "Daily Hot Special",
    description: "Rotating daily special — confirm at the window.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("food12.jpg"),
    imageAlt: "Daily special",
    optionGroups: [...ANGIES_ADD_EXTRA_SUB],
  },
  {
    id: "side-rice",
    active: true,
    category: "Sides",
    sortOrder: 1,
    name: "Rice",
    description: "Mexican rice.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food3.jpg"),
    imageAlt: "Rice",
  },
  {
    id: "side-beans",
    active: true,
    category: "Sides",
    sortOrder: 2,
    name: "Beans",
    description: "Refried or whole beans — confirm at the window.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food15.jpg"),
    imageAlt: "Beans",
  },
  {
    id: "catering-event",
    active: true,
    category: "Catering",
    sortOrder: 1,
    name: "Event Catering",
    description: "Catering and event request — confirm menu and pricing with the owner.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("food16.png"),
    imageAlt: "Catering spread",
    optionGroups: [...ANGIES_ADD_EXTRA_SUB],
  },
];
